FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

ENV REACT_APP_API_BASE_URL /
ENV REACT_APP_WEBSOCKET_BASE_URL /ws

COPY . .
RUN npm run build

FROM nginx:1.29.1-alpine-slim

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
