services:
  history-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: history-service-prod
    restart: unless-stopped
    ports:
      - '4040:4040'
    environment:
      - NODE_ENV=production
      - PORT=4040
    
    db:
      image: mongo:8.0
      container_name: history-service-db
      ports:
        - '4041:27017'
    volumes:
      - history-service-db-data:/data/db
      - ./src/database/init:/docker-entrypoint-initdb.d

