FROM alpine:latest  

RUN apk update && \
    apk add build-base 

RUN apk add --no-cache python3 py3-pip \
    && ln -sf python3 /usr/bin/python \
    && ln -sf pip3 /usr/bin/pip

WORKDIR /app

COPY ./requirements.txt ./
RUN pip3 install --break-system-packages -r ./requirements.txt

COPY . .

RUN chmod +x ./solutions/compile_all.sh

CMD ["tail", "-f", "/dev/null"]
