apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-execution-service
  template:
    metadata:
      labels:
        app: code-execution-service
    spec:
      containers:
        - name: code-execution-service
          image: asia-southeast1-docker.pkg.dev/peerprep-g26-2025/peerprep/code-execution-service:latest
          ports:
            - containerPort: 4050
          envFrom:
            - secretRef:
                name: code-execution-service-secret
