apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
        - name: collaboration-service
          image: asia-southeast1-docker.pkg.dev/peerprep-g26-2025/peerprep/collaboration-service:latest
          ports:
            - containerPort: 4030
          envFrom:
            - secretRef:
                name: collaboration-service-secret
