apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: asia-southeast1-docker.pkg.dev/peerprep-g26-2025/peerprep/matching-service:latest
          ports:
            - containerPort: 4020
          envFrom:
            - secretRef:
                name: matching-service-secret
