apiVersion: v1
kind: Service
metadata:
  name: matching-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"4020":"websocket-backendconfig"}}'
spec:
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 4020
      targetPort: 4020
  type: ClusterIP
