apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: $GCP_REGION/$PROJECT_ID/$REPO_NAME/user-service:$SHORT_SHA
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: user-service-secret
