services:
  code-execution-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: code-execution-service-prod
    restart: unless-stopped
    ports:
      - "4050:4050"
    environment:
      - NODE_ENV=production
      - PORT=4050
      - BACKEND_BASE_URL=http://nginx
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
